### ISSUE TITLE
script sql

### ISSUE THREAD

**Issue by MancioLollo** [GiovanniRaseraF/Castoro#2]
Eseguendo lo script da psql : 
DROP DB 
CREATE DB
DROP TABLE IF EXISTS user( --> ERRORE: errore di sintassi a o presso "user"

CREATE TABLE stories

durante la creazione di "user_has_stories"
REFERENCES user(id_user) --> ERRORE: errore di sintassi a o presso "user"

**Comment by GiovanniRaseraF** [comment]
prova a fare:
```sql
SET search_path to DB;
```

**Comment by GiovanniRaseraF** [comment]
e poi esegui le query di creazione delle tabelle

**Comment by MancioLollo** [comment]
Esegue il set ma restituisce gli stessi errori.
Comunque io ho tolto lo schema dallo script che dava mysql wb perche' abbiamo poche tabelle e il db e' piccolo, non so se l'errore e' un effetto collaterale di questo fatto, devo guardare.

**Comment by MancioLollo** [comment]
appunto, ho rimesso create schema al posto di create database.
lasciato set search_path e comando script
